name: Deploy to Azure
run-name: "Run ${{ github.run_id }}, triggered by ${{ github.actor }}"

on:
  workflow_dispatch:  # Manually triggered

jobs:
  build-and-push-acr:
    name: Build and Push Images to ACR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry (ACR)
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build and push backend image
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/backend:latest ./backend
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/backend:latest

      - name: Build and push frontend image
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/frontend:latest ./frontend
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/frontend:latest

  deploy-backend:
    name: Deploy Backend to Azure Web App
    runs-on: ubuntu-latest
    needs: build-and-push-acr
    steps:
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy backend container
        run: |
          az webapp config container set --name ${{ secrets.AZURE_BACKEND_APP_NAME }} \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --docker-custom-image-name ${{ secrets.ACR_NAME }}.azurecr.io/backend:latest \
            --docker-registry-server-url https://${{ secrets.ACR_NAME }}.azurecr.io \
            --docker-registry-server-user ${{ secrets.ACR_USERNAME }} \
            --docker-registry-server-password ${{ secrets.ACR_PASSWORD }}

      - name: Restart backend web app
        run: |
          az webapp restart --name ${{ secrets.AZURE_BACKEND_APP_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }}

  deploy-frontend:
    name: Deploy Frontend to Azure Web App
    runs-on: ubuntu-latest
    needs: build-and-push-acr
    steps:
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy frontend container
        run: |
          az webapp config container set --name ${{ secrets.AZURE_FRONTEND_APP_NAME }} \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --docker-custom-image-name ${{ secrets.ACR_NAME }}.azurecr.io/frontend:latest \
            --docker-registry-server-url https://${{ secrets.ACR_NAME }}.azurecr.io \
            --docker-registry-server-user ${{ secrets.ACR_USERNAME }} \
            --docker-registry-server-password ${{ secrets.ACR_PASSWORD }}

      - name: Restart frontend web app
        run: |
          az webapp restart --name ${{ secrets.AZURE_FRONTEND_APP_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }}
